weatherProject/weatherProject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include("weatherapp.urls") ),
    path("",include("django.contrib.auth.urls") ),


]

weatherProject/weatherapp/urls.py
from django.urls import path
from . import views

app_name='weatherapp'

urlpatterns = [
    path("", views.home, name="home"),
    path("search/", views.search, name="search"),
    path("signup/", views.signup, name="signup"),
    path("mycity/", views.mycity, name="mycity"),
    path("chcity/", views.chcity, name="chcity"),
    path("chpassword/", views.chpassword, name="chpassword"),

    
    

    
]

weatherProject/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <title>Weather App</title>
    <link rel="stylesheet" href="{% static 'weatherapp/style.css' %}">
    
</head>

<body>
    <header class="p-3 text-bg-primary">
        <div class="container">
          <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
              {% if user.is_anonymous %}
              <li><a href="{%url 'weatherapp:home'%}" class="btn btn-outline-light mx-2">Home</a></li>
              <li><a href="{%url 'weatherapp:search'%}" class="nav-link px-2 text-white mx-2">Search</a></li>
              {% else %}
              <li><a href="{%url 'weatherapp:home'%}" class="btn btn-outline-light mx-2">Home</a></li>
              <li><a href="{%url 'weatherapp:search'%}" class="nav-link px-2 text-white ">Search</a></li>
              <li><a href="{%url 'weatherapp:mycity'%}" class="nav-link px-2 text-white ">My City</a></li>
              {% endif %}
              
            </ul>

            <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
              <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                {% if user.is_anonymous %}
                <li><a href="{%url 'login'%}" class="btn btn-outline-light mx-2">Log in</a></li>
                <li><a href="{%url 'weatherapp:signup'%}" class="btn btn-info mx-2">Sign up</a></li>
                {% else %}
                <li><a href="{%url 'login'%}" class="btn btn-outline-light mx-2">{{user.username}}</a></li>
                <li><a href="{%url 'logout'%}?next=/" class="btn btn-danger ">Log Out</a></li>

                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </header>

      
{% block content %}

{% endblock %}
</body>
</html>